# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        brands:
            uri_prefix: /images/brands
            upload_destination: '%kernel.project_dir%/public/images/brands'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        shoes:
            uri_prefix: /images/shoes
            upload_destination: '%kernel.project_dir%/public/images/shoes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer